#!/usr/bin/env bash
# =============================================================================
# gcm-reset.sh — Full cleanup script for GCM (Git Config Manager)
#
# What this script cleans:
#   1. Git global identity (user.name, user.email, signingkey, commit.gpgsign)
#   2. Git local identity for the current repo (if inside a git repo)
#   3. All GCM profiles, tokens, config, backups, cache, and logs
#   4. All SSH keys generated by GCM (id_ed25519_<profile> / id_rsa_<profile>)
#   5. All GPG keys referenced by GCM profiles
#   6. GCM credential helper from git global config
#   7. GCM shell hooks from ~/.zshrc / ~/.bashrc / ~/.bash_profile
#
# Usage:
#   bash scripts/gcm-reset.sh              # Interactive (asks what to clean)
#   bash scripts/gcm-reset.sh --all        # Clean everything without prompts
#   bash scripts/gcm-reset.sh --dry-run    # Show what would be deleted
# =============================================================================

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

ok()   { echo -e "${GREEN}✓${RESET} $*"; }
warn() { echo -e "${YELLOW}⚠${RESET} $*"; }
info() { echo -e "${CYAN}→${RESET} $*"; }
step() { echo -e "\n${BOLD}$*${RESET}"; }

# Flags
ALL=false
DRY_RUN=false

for arg in "$@"; do
  case "$arg" in
    --all)     ALL=true ;;
    --dry-run) DRY_RUN=true ;;
    -h|--help)
      echo "Usage: $0 [--all] [--dry-run]"
      echo "  --all      Clean everything without asking"
      echo "  --dry-run  Show what would be deleted, do nothing"
      exit 0
      ;;
    *) warn "Unknown argument: $arg" ;;
  esac
done

# run <desc> <cmd...> — executes cmd, ignores errors, supports dry-run
run() {
  local desc="$1"; shift
  if $DRY_RUN; then
    info "[dry-run] $desc"
    return 0
  fi
  "$@" 2>/dev/null || true
  ok "$desc"
}

# ask <question> → 0=yes 1=no — bash 3 compatible (no ${var,,})
ask() {
  $ALL && return 0
  local answer
  printf "${CYAN}?${RESET} %s [y/N]: " "$1"
  read -r answer
  answer=$(echo "$answer" | tr '[:upper:]' '[:lower:]')
  [[ "$answer" == "y" || "$answer" == "yes" ]]
}

# Header
echo -e "${BOLD}╔══════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}║        GCM Full Reset / Cleanup          ║${RESET}"
echo -e "${BOLD}╚══════════════════════════════════════════╝${RESET}"
echo

$DRY_RUN && { warn "DRY RUN — nothing will actually be deleted"; echo; }
! $ALL && ! $DRY_RUN && { warn "This will permanently delete ALL GCM data and git identity config."; echo; }

# Collect GPG key IDs and SSH patterns from profiles BEFORE deleting them
GCM_DIR="${HOME}/.gcm"
PROFILES_DIR="${GCM_DIR}/profiles"
GPG_KEY_IDS=()
SSH_KEY_PATTERNS=()

if [[ -d "$PROFILES_DIR" ]]; then
  for yaml in "$PROFILES_DIR"/*.yaml; do
    [[ -f "$yaml" ]] || continue
    profile_name=$(basename "$yaml" .yaml)
    SSH_KEY_PATTERNS+=("${HOME}/.ssh/id_ed25519_${profile_name}")
    SSH_KEY_PATTERNS+=("${HOME}/.ssh/id_rsa_${profile_name}")
    gpg_key=$(grep -E '^\s*key_id:' "$yaml" 2>/dev/null | awk '{print $2}' | tr -d '"' || true)
    [[ -n "$gpg_key" ]] && GPG_KEY_IDS+=("$gpg_key")
  done
fi

# Step 1: Git global identity
step "Step 1/7: Git global identity"
if ask "Clear git global user.name, user.email, signingkey, gpgsign?"; then
  run "Unset git global user.name"       git config --global --unset-all user.name
  run "Unset git global user.email"      git config --global --unset-all user.email
  run "Unset git global user.signingkey" git config --global --unset-all user.signingkey
  run "Unset git global commit.gpgsign"  git config --global --unset-all commit.gpgsign
  run "Unset git global gpg.format"      git config --global --unset-all gpg.format
  run "Unset git global core.sshCommand" git config --global --unset-all core.sshCommand
else
  info "Skipped git global identity"
fi

# Step 2: Git local identity (current repo)
step "Step 2/7: Git local identity (current repo)"
if git rev-parse --is-inside-work-tree &>/dev/null; then
  if ask "Clear git local identity in current repo?"; then
    run "Unset git local user.name"       git config --local --unset-all user.name
    run "Unset git local user.email"      git config --local --unset-all user.email
    run "Unset git local user.signingkey" git config --local --unset-all user.signingkey
    run "Unset git local commit.gpgsign"  git config --local --unset-all commit.gpgsign
    run "Remove .gcm-profile marker"      rm -f "$(git rev-parse --show-toplevel)/.gcm-profile"
  else
    info "Skipped git local identity"
  fi
else
  info "Not inside a git repo — skipping local config"
fi

# Step 3: GCM data
step "Step 3/7: GCM data (profiles, tokens, config, backups, cache, logs)"
if ask "Delete ALL GCM profiles, tokens, backups, cache, and logs?"; then
  run "Remove GCM profiles"  rm -rf "${GCM_DIR}/profiles"
  run "Remove GCM tokens"    rm -rf "${GCM_DIR}/tokens"
  run "Remove GCM backups"   rm -rf "${GCM_DIR}/backups"
  run "Remove GCM cache"     rm -rf "${GCM_DIR}/cache"
  run "Remove GCM logs"      rm -rf "${GCM_DIR}/logs"
  run "Remove GCM templates" rm -rf "${GCM_DIR}/templates"
  run "Remove GCM config"    rm -f  "${GCM_DIR}/config.yaml"
else
  info "Skipped GCM data"
fi

# Step 4: SSH keys generated by GCM
step "Step 4/7: SSH keys generated by GCM"
SSH_FOUND=()
for pattern in "${SSH_KEY_PATTERNS[@]+"${SSH_KEY_PATTERNS[@]}"}"; do
  [[ -f "$pattern" ]]       && SSH_FOUND+=("$pattern")
  [[ -f "${pattern}.pub" ]] && SSH_FOUND+=("${pattern}.pub")
done

if [[ ${#SSH_FOUND[@]} -eq 0 ]]; then
  info "No GCM-generated SSH keys found"
else
  echo "  Found SSH keys:"
  for f in "${SSH_FOUND[@]}"; do echo "    $f"; done
  if ask "Delete these SSH keys?"; then
    for f in "${SSH_FOUND[@]}"; do run "Remove $f" rm -f "$f"; done
  else
    info "Skipped SSH key deletion"
  fi
fi

# Step 5: GPG keys generated by GCM
step "Step 5/7: GPG keys generated by GCM"
if [[ ${#GPG_KEY_IDS[@]} -eq 0 ]]; then
  info "No GCM GPG key IDs found in profiles"
else
  echo "  Found GPG key IDs:"
  for kid in "${GPG_KEY_IDS[@]}"; do echo "    $kid"; done
  if ask "Delete these GPG keys from your keychain?"; then
    for kid in "${GPG_KEY_IDS[@]}"; do
      run "Delete GPG secret key $kid" gpg --batch --yes --delete-secret-and-public-key "$kid"
    done
  else
    info "Skipped GPG key deletion"
  fi
fi

# Step 6: GCM credential helper
step "Step 6/7: Git credential helper (GCM)"
GCM_CRED=$(git config --global "credential.https://github.com.helper" 2>/dev/null || true)
if echo "$GCM_CRED" | grep -qi "gcm"; then
  if ask "Remove GCM credential helper from git global config?"; then
    run "Unset credential helper for github.com" \
      git config --global --unset-all "credential.https://github.com.helper"
  else
    info "Skipped credential helper removal"
  fi
else
  info "GCM credential helper not found — skipping"
fi

# Step 7: Shell hooks
step "Step 7/7: GCM shell hooks"
SHELL_FILES=("${HOME}/.zshrc" "${HOME}/.bashrc" "${HOME}/.bash_profile" "${HOME}/.profile")
HOOK_FOUND=false
for rc in "${SHELL_FILES[@]}"; do
  [[ -f "$rc" ]] || continue
  grep -q "gcm" "$rc" 2>/dev/null && { HOOK_FOUND=true; echo "  Found GCM lines in: $rc"; }
done

if ! $HOOK_FOUND; then
  info "No GCM shell hooks found"
else
  if ask "Remove GCM hook lines from shell rc files?"; then
    for rc in "${SHELL_FILES[@]}"; do
      [[ -f "$rc" ]] || continue
      if grep -q "gcm" "$rc" 2>/dev/null; then
        if $DRY_RUN; then
          info "[dry-run] Would remove GCM lines from $rc"
        else
          cp "$rc" "${rc}.gcm-reset-backup"
          grep -v "gcm" "$rc" > "${rc}.tmp" && mv "${rc}.tmp" "$rc"
          ok "Removed GCM lines from $rc (backup: ${rc}.gcm-reset-backup)"
        fi
      fi
    done
  else
    info "Skipped shell hook removal"
  fi
fi

# Summary
echo
echo -e "${BOLD}──────────────────────────────────────────${RESET}"
echo -e "${GREEN}${BOLD}✅ Reset complete!${RESET}"
echo
echo "Verify:"
echo "  git config --global user.name   → should be empty"
echo "  git config --global user.email  → should be empty"
echo "  ls ~/.gcm/profiles/             → should be empty"
echo
echo "To set up again:"
echo "  gcm setup"
